date = '20180315';
task = 'CO';
monkey = 'Butter';
array = 'cuneate';
number = 2;
cds = easyCDS(monkey, task, date, array, number, true);
outpath = getCdsSavePath(monkey, date, getTask(task));
cdsPath = [outpath,monkey, '_', task, '_', date,'_',num2str(number), '_CDS_sorted.mat'];
mkdir(outpath);
save(cdsPath, 'cds', '-v7.3');