pds = ex.bin.pdData;
cuneatePD = pds(strcmp(pds.array, 'RightCuneate'), :);
tunedCuneate = cuneatePD(cuneatePD.posIsTuned | cuneatePD.velIsTuned,:);
posTunedCuneate = cuneatePD(cuneatePD.posIsTuned,:);
velTunedCuneate = cuneatePD(cuneatePD.velIsTuned,:);
% forceTunedCuneate = cuneatePD(cuneatePD.forceIsTuned,:);
% forceCI = forceTunedCuneate.forceDirCI;
% forceCIsize = forceCI(:,2) - forceCI(:,1);
% forceDirTuned = forceTunedCuneate(forceCIsize < pi/4,:);
posCI = posTunedCuneate.posDirCI;
velCI = velTunedCuneate.velDirCI;
posCIsize = posCI(:,2) - posCI(:,1);
velCIsize = velCI(:,2) - velCI(:,1);
posDirTuned = posTunedCuneate(posCIsize <pi/4,:);
velDirTuned = velTunedCuneate(velCIsize<pi/4,:);
disp(['Pos Tuned %', num2str(height(posTunedCuneate)*100/height(cuneatePD) )]);
disp(['Velocity Tuned %', num2str(height(velTunedCuneate)*100/height(cuneatePD))]);
disp(['PosDir Tuned %',num2str(height(posDirTuned)*100/height(cuneatePD))]);
disp(['VelDir Tuned %', num2str(height(velDirTuned)*100/height(cuneatePD))]);